# Prometheus configuration file
global:
  scrape_interval: 15s # Default scrape interval
  evaluation_interval: 15s # Default evaluation interval

# Alerting rules
rule_files:
  - "/etc/prometheus/alert_rules.yml"

# Scrape configurations
scrape_configs:
  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    scrape_interval: 30s
    metrics_path: /metrics

  # Sentiment Analysis Application
  - job_name: 'sentiment-app'
    static_configs:
      - targets: ['sentiment-app:5000']
    scrape_interval: 15s
    metrics_path: /metrics
    scrape_timeout: 10s

  # Node Exporter for system metrics
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 30s
    metrics_path: /metrics

# Alerting configuration (optional)
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093